project:
  type: website
  output-dir: docs

website:
  title: "Meghana | Business Analytics"
  favicon: images/favicon.ico
  navbar:
    logo: images/logo.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Reflection"
        href: reflection.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - text: "CV"
        href: cv/meghana-cv.pdf
        target: _blank
      - icon: github
        href: https://github.com/55megh
        target: _blank
  page-footer:
    center: "© 2025 Meghana | Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: [flatly, styles.scss]
    toc: true



