project:
  type: website
  output-dir: docs

website:
  title: "MEGHANA MURTHY"
  description: "A Business Analytics portfolio by Meghana Murthy"
  favicon: images/favicon.ico
  site-url: https://55megh.github.io/my-portfolio
  open-graph: true
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    border: true
    background: dark
    foreground: light
    left: |
      Powered by [{{< fa brands quarto >}} Quarto](https://quarto.org){target="_blank"}
    center: |
      &copy; 2025 [Meghana Murthy](https://55megh.github.io/my-portfolio){target="_blank"}
    right: |
      MSc Business Analytics | DCU
  navbar:
    search: true
    background: dark
    foreground: light
    logo: images/logo.png
    logo-alt: "Meghana Murthy logo"
    left:
      - text: "home"
        href: index.qmd
      - text: "about"
        href: about.qmd
      - text: "projects"
        href: projects/index.qmd
      - text: "reflection"
        href: reflection.qmd
      - text: "contact"
        href: contact.qmd
    right:
      - text: "CV"
        href: cv/meghana-cv.pdf
        target: _blank
      - text: '{{< fa brands linkedin >}}'
        href: "https://www.linkedin.com/in/meghana-v-murthy/"
        target: _blank
      - text: '{{< fa brands github >}}'
        href: "https://github.com/55megh"
        target: _blank
      - text: '{{< fa envelope >}}'
        href: "mailto:mvmeghana9@gmail.com"

format:
  html:
    theme: [flatly, styles.scss]
    mainfont: Nunito
    toc: true
    code-copy: true
    code-overflow: wrap
    anchor-sections: true
    link-external-newwindow: true
    fig-align: center
    syntax-highlighting:
      light: github-light
      dark: github-dark

mermaid:
  theme: neutral

execute:
  freeze: true





